global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from OTel Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  # Scrape Prometheus self-metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Postgres exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']