global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://localhost:9090/api/v1/write

scrape_configs:
  # Scrape metrics directly from FastAPI /metrics endpoint
  - job_name: 'cifar10_api'
    static_configs:
      - targets: ['api:7860']
    metrics_path: '/metrics'
    metric_relabel_configs:
      - source_labels: [ http_server_name ]
        target_label: http_server_name
        replacement: "api"

  # Scrape metrics from OTel Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  # Scrape Prometheus self-metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Postgres exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
